apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: payment
  labels:
    app: payment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: payment

  template:
    metadata:
      labels:
        app: payment

    spec:
      containers:
      - name: payment
        image: nginx:1.27
        ports:
        - containerPort: 80
